### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by davmcgregor** [davmcgregor/super-cars#1]
- [x] Create mock data
- [x] Style responsive <SelectedCar> component in line with wireframe
- [x] ensure mechanism to reset results (e.g. query is empty, exit button)
- [x] Style <Search> component in line with design (e.g. dropdown)
- [x] Set up context API and provider 
- [x] Add loading and error state (optional here?)
- [x] Create integration b/w component, state, and methods
- [x] Check styling and components refactored into smaller components where helpful
- [x] Refactor CSS selectors where possible e.g. carDetailsItem <span>
- [x] Shorten CSS classes where possible
- [x] Avoid divitis - e.g. results as ul, li list, sections 
- [x] Add additional UX for car selection from dropdown
- [x] Check spacing edge cases, e.g. on 'Volkswagen Amarok'

Final steps:
- [x] check for console errors 
- [x] ensure import orders are consistent
- [x] check accessibility and aria labelling
- [x] basic unit tests for each component (and utils)
- [x] Check no TS errors
- [x] Final check that AC met
